"""initial_product_schema

Revision ID: e419f4a6e5ba
Revises:
Create Date: 2026-09-24 23:00:48.909620
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e419f4a6e5ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('max_user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('default_contact', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('ADMIN','GUARD','RESIDENT')", name='ck_accounts_role'),
    sa.PrimaryKeyConstraint('max_user_id')
    )
    op.create_index('ix_accounts_role_active', 'accounts', ['role', 'is_active'], unique=False)
    op.create_table('max_webhook_events',
    sa.Column('event_key', sa.String(length=160), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('event_key')
    )
    op.create_table('residential_complexes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complex_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('target_id', sa.String(length=120), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['accounts.max_user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['complex_id'], ['residential_complexes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_complex_created', 'audit_events', ['complex_id', 'created_at'], unique=False)
    op.create_table('buildings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complex_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['complex_id'], ['residential_complexes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('complex_id', 'name', name='uq_buildings_complex_name')
    )
    op.create_index(op.f('ix_buildings_complex_id'), 'buildings', ['complex_id'], unique=False)
    op.create_table('checkpoints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complex_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['complex_id'], ['residential_complexes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('complex_id', 'name', name='uq_checkpoints_complex_name')
    )
    op.create_index(op.f('ix_checkpoints_complex_id'), 'checkpoints', ['complex_id'], unique=False)
    op.create_table('complex_admins',
    sa.Column('complex_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['complex_id'], ['residential_complexes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.max_user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('complex_id', 'user_id')
    )
    op.create_table('guard_profiles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('complex_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('verified_by', sa.BigInteger(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('INVITED','PENDING','VERIFIED','REJECTED','DEACTIVATED')", name='ck_guard_profiles_status'),
    sa.ForeignKeyConstraint(['complex_id'], ['residential_complexes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.max_user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['accounts.max_user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('ix_guard_profiles_complex_status', 'guard_profiles', ['complex_id', 'status'], unique=False)
    op.create_table('registry_imports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complex_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('rows_json', sa.JSON(), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['complex_id'], ['residential_complexes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['accounts.max_user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_registry_imports_complex_created', 'registry_imports', ['complex_id', 'created_at'], unique=False)
    op.create_table('apartments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('building_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'number', name='uq_apartments_building_number')
    )
    op.create_index(op.f('ix_apartments_building_id'), 'apartments', ['building_id'], unique=False)
    op.create_table('guard_checkpoints',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('checkpoint_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['checkpoints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['guard_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'checkpoint_id')
    )
    op.create_table('guard_invites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('complex_id', sa.Uuid(), nullable=False),
    sa.Column('checkpoint_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['checkpoints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['complex_id'], ['residential_complexes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['accounts.max_user_id'], ),
    sa.ForeignKeyConstraint(['used_by'], ['accounts.max_user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_hash')
    )
    op.create_index('ix_guard_invites_expiry', 'guard_invites', ['expires_at', 'used_at'], unique=False)
    op.create_table('guard_shifts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complex_id', sa.Uuid(), nullable=False),
    sa.Column('checkpoint_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=True),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("kind IN ('RECURRING','ONE_TIME','REPLACEMENT')", name='ck_guard_shifts_kind'),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['checkpoints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['complex_id'], ['residential_complexes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['accounts.max_user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['guard_profiles.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_guard_shifts_dates', 'guard_shifts', ['starts_on', 'ends_on'], unique=False)
    op.create_index('ix_guard_shifts_guard_checkpoint', 'guard_shifts', ['user_id', 'checkpoint_id'], unique=False)
    op.create_table('registry_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('apartment_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('normalized_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apartment_id', 'normalized_name', name='uq_registry_apartment_person')
    )
    op.create_index(op.f('ix_registry_entries_apartment_id'), 'registry_entries', ['apartment_id'], unique=False)
    op.create_index('ix_registry_name', 'registry_entries', ['normalized_name'], unique=False)
    op.create_table('resident_visit_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complex_id', sa.Uuid(), nullable=False),
    sa.Column('resident_id', sa.BigInteger(), nullable=False),
    sa.Column('apartment_id', sa.Uuid(), nullable=False),
    sa.Column('checkpoint_id', sa.Uuid(), nullable=False),
    sa.Column('visitor_type', sa.String(length=24), nullable=False),
    sa.Column('visitor_name', sa.String(length=200), nullable=False),
    sa.Column('visitor_car_number', sa.String(length=24), nullable=True),
    sa.Column('resident_contact', sa.String(length=80), nullable=False),
    sa.Column('estimated_arrival_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.BigInteger(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('ACTIVE','PASSED','REJECTED','CANCELLED','EXPIRED','DELETED')", name='ck_visit_requests_status'),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['checkpoints.id'], ),
    sa.ForeignKeyConstraint(['complex_id'], ['residential_complexes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resident_id'], ['accounts.max_user_id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['accounts.max_user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_visit_queue', 'resident_visit_requests', ['checkpoint_id', 'status', 'created_at'], unique=False)
    op.create_index('ix_visit_resident', 'resident_visit_requests', ['resident_id', 'created_at'], unique=False)
    op.create_index('ix_visit_search_car', 'resident_visit_requests', ['visitor_car_number'], unique=False)
    op.create_index('ix_visit_search_name', 'resident_visit_requests', ['visitor_name'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('text', sa.String(length=1500), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','PROCESSING','SENT','FAILED')", name='ck_notifications_status'),
    sa.ForeignKeyConstraint(['recipient_id'], ['accounts.max_user_id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['resident_visit_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key', name='uq_notifications_dedupe')
    )
    op.create_index('ix_notifications_delivery', 'notifications', ['status', 'next_attempt_at'], unique=False)
    op.create_index(op.f('ix_notifications_request_id'), 'notifications', ['request_id'], unique=False)
    op.create_table('resident_apartments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('apartment_id', sa.Uuid(), nullable=False),
    sa.Column('registry_entry_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registry_entry_id'], ['registry_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.max_user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apartment_id', 'user_id', name='uq_resident_apartment_pair'),
    sa.UniqueConstraint('registry_entry_id', name='uq_resident_registry_entry')
    )
    op.create_index('ix_resident_apartments_user', 'resident_apartments', ['user_id'], unique=False)
    op.create_table('visit_request_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['accounts.max_user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['resident_visit_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_visit_events_request_created', 'visit_request_events', ['request_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_visit_request_events_request_id'), 'visit_request_events', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visit_request_events_request_id'), table_name='visit_request_events')
    op.drop_index('ix_visit_events_request_created', table_name='visit_request_events')
    op.drop_table('visit_request_events')
    op.drop_index('ix_resident_apartments_user', table_name='resident_apartments')
    op.drop_table('resident_apartments')
    op.drop_index(op.f('ix_notifications_request_id'), table_name='notifications')
    op.drop_index('ix_notifications_delivery', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_visit_search_name', table_name='resident_visit_requests')
    op.drop_index('ix_visit_search_car', table_name='resident_visit_requests')
    op.drop_index('ix_visit_resident', table_name='resident_visit_requests')
    op.drop_index('ix_visit_queue', table_name='resident_visit_requests')
    op.drop_table('resident_visit_requests')
    op.drop_index('ix_registry_name', table_name='registry_entries')
    op.drop_index(op.f('ix_registry_entries_apartment_id'), table_name='registry_entries')
    op.drop_table('registry_entries')
    op.drop_index('ix_guard_shifts_guard_checkpoint', table_name='guard_shifts')
    op.drop_index('ix_guard_shifts_dates', table_name='guard_shifts')
    op.drop_table('guard_shifts')
    op.drop_index('ix_guard_invites_expiry', table_name='guard_invites')
    op.drop_table('guard_invites')
    op.drop_table('guard_checkpoints')
    op.drop_index(op.f('ix_apartments_building_id'), table_name='apartments')
    op.drop_table('apartments')
    op.drop_index('ix_registry_imports_complex_created', table_name='registry_imports')
    op.drop_table('registry_imports')
    op.drop_index('ix_guard_profiles_complex_status', table_name='guard_profiles')
    op.drop_table('guard_profiles')
    op.drop_table('complex_admins')
    op.drop_index(op.f('ix_checkpoints_complex_id'), table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_index(op.f('ix_buildings_complex_id'), table_name='buildings')
    op.drop_table('buildings')
    op.drop_index('ix_audit_complex_created', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('residential_complexes')
    op.drop_table('max_webhook_events')
    op.drop_index('ix_accounts_role_active', table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
